// UI Components - single source of truth for all component exports
export { About } from './About'
export type { AboutProps } from './About'
export { Accordion } from './Accordion/Accordion'
export type { AccordionProps, AccordionItem } from './Accordion/Accordion'
export { Badge } from './Badge/Badge'
export { Button } from './Button/Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button/Button'
export { Card } from './Card/Card'
export type { CardProps } from './Card/Card'
export { Chip, ChipGroup } from './Chip'
export type { ChipProps, ChipGroupProps, ChipItem } from './Chip'
export { Dialog } from './Dialog/Dialog'
export { Footer } from './Footer'
export type { FooterProps } from './Footer'
export { Hero } from './Hero/Hero'
export type { HeroProps } from './Hero/Hero'
export { Icon } from './Icon'
export type { IconProps, IconSize, IconColor } from './Icon'
export { IconButton } from './IconButton'
export type { IconButtonProps, IconButtonSize, IconButtonVariant } from './IconButton'
export { InterestingFacts } from './InterestingFacts'
export type { InterestingFactsProps } from './InterestingFacts'
export { Toggle } from './Toggle/Toggle'
